// This file is automatic generated by scripts/genMappings.js
import {Props as props0} from "../src/./pages/index"
import {Props as props1} from "../src/./pages/posts/_id/index"
import {Props as props2} from "../src/./pages/posts/index"
declare namespace PagePropsType {
type index = props0
type postsX_id = props1
type posts = props2
}