/* tslint:disable */
/* eslint-disable */
/**
 * RailsTsReact
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostSummary
 */
export interface PostSummary {
    /**
     * 
     * @type {number}
     * @memberof PostSummary
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PostSummary
     */
    title: string;
}

export function PostSummaryFromJSON(json: any): PostSummary {
    return PostSummaryFromJSONTyped(json, false);
}

export function PostSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'title': json['title'],
    };
}

export function PostSummaryToJSON(value?: PostSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
    };
}


