// This file is automatic generated by scripts/genMappings.js
import _page0 from "./pages/index"
import _page1 from "./pages/posts/_id/index"
import _page2 from "./pages/posts/index"
export let Pages = {
"index": _page0,
"posts/_id": _page1,
"posts": _page2,
} as Record<string, PageComponent<any>>;