openapi: '3.0.2'
info:
  title: RailsTsReact
  version: '1.0'
servers:
  - url: https://localhost:3000/api
paths:
  /posts:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/post'
  /posts/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/post'
components:
  schemas:
    post:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
      required: [id, title, content]
