openapi: 3.0.2
info:
  title: RailsTsReact
  version: 0.0.0
paths:
  /posts:
    get:
      tags:
        - posts
      operationId: getPosts
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PostSummary'
  '/posts/{id}':
    get:
      tags:
        - posts
      operationId: getPost
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
  /users/current:
    get:
      tags:
        - users
      operationId: getUsersCurrent
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    PostSummary:
      type: object
      properties:
        id:
          type: integer
          format: int32
        title:
          type: string
      required:
        - id
        - title
    Post:
      type: object
      properties:
        id:
          type: integer
          format: int32
        title:
          type: string
        content:
          type: string
      required:
        - id
        - title
        - content
    User:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
      required:
        - id
        - name
