openapi: 3.0.2
info:
  title: RailsTsReact
  version: '1.0'
  contact:
    name: cumet04
  description: RailsTsReact
servers:
  - url: 'https://localhost:3000/api'
paths:
  /posts:
    get:
      tags:
        - posts
      operationId: get-posts
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PostSummary'
      description: available post list
  '/posts/{id}':
    get:
      tags:
        - posts
      operationId: get-posts-id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
      description: post detail
  /users/current:
    get:
      summary: Your GET endpoint
      tags:
        - users
      operationId: get-users-current
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      description: current user
components:
  schemas:
    PostSummary:
      type: object
      title: PostSummary
      properties:
        id:
          type: integer
        title:
          type: string
      required:
        - id
        - title
    Post:
      title: Post
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
      required:
        - id
        - title
        - content
    User:
      title: User
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
        - name
tags:
  - name: posts
  - name: users
