openapi: 3.0.2
info:
  title: RailsTsReact
  version: '1.0'
  contact:
    name: cumet04
  description: RailsTsReact
servers:
  - url: 'https://localhost:3000/api'
paths:
  /posts:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PostSummary'
      description: available post list
      tags:
        - posts
      operationId: get_posts
  '/posts/{id}':
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
      description: post detail
      operationId: get_posts_id
      tags:
        - posts
components:
  schemas:
    PostSummary:
      type: object
      title: PostSummary
      properties:
        id:
          type: integer
        title:
          type: string
      required:
        - id
        - title
    Post:
      title: Post
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        content:
          type: string
      required:
        - id
        - title
        - content
tags:
  - name: posts
